'use client';
import { apiUrl } from '@/lib/api-url';
import { useEffect, useState } from 'react';
import { KeyRound, Shield, User } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import { cachedApiGet, invalidateCacheTags } from '@/lib/api-cache';
import { PageHeader } from '@/components/shared/page-header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { Turnstile } from '@/components/shared/turnstile';
import { toast } from 'sonner';

export default function StudentSettingsPage() {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [captchaToken, setCaptchaToken] = useState<string | null>(null); const [captchaKey, setCaptchaKey] = useState(0); const [changing, setChanging] = useState(false);
  useEffect(() => { void (async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session) return setLoading(false); try { setName((await cachedApiGet<{ display_name: string }>('/api/profile', 300000, ['profile'])).display_name); } finally { setEmail(session.user.email ?? ''); setLoading(false); } })(); }, []);
  const save = async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session) return; setSaving(true); try { const response = await fetch(`${apiUrl}/api/profile`, { method: 'PATCH', headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ display_name: name }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail); invalidateCacheTags('profile'); setName(payload.display_name); window.dispatchEvent(new CustomEvent('wahamath-profile-updated', { detail: payload.display_name })); toast.success('Profil enregistré'); } catch (error) { toast.error('Enregistrement impossible', { description: error instanceof Error ? error.message : undefined }); } finally { setSaving(false); } };
  const changePassword = async () => { if (!currentPassword) return toast.error('Saisissez votre mot de passe actuel.'); if (newPassword.length < 8 || !/[A-Za-z]/.test(newPassword) || !/\d/.test(newPassword)) return toast.error('Utilisez au moins 8 caractères, une lettre et un chiffre.'); if (newPassword !== confirmation) return toast.error('Les mots de passe ne correspondent pas'); if (!captchaToken) return toast.error('Veuillez confirmer que vous n’êtes pas un robot.'); setChanging(true); try { const { error: verificationError } = await supabase.auth.signInWithPassword({ email, password: currentPassword, options: { captchaToken } }); if (verificationError) throw new Error('Mot de passe actuel incorrect.'); const { error } = await supabase.auth.updateUser({ password: newPassword }); if (error) throw error; setCurrentPassword(''); setNewPassword(''); setConfirmation(''); toast.success('Mot de passe modifié', { description: 'Votre nouveau mot de passe est actif.' }); } catch (error) { toast.error('Modification impossible', { description: error instanceof Error ? error.message : undefined }); } finally { setChanging(false); setCaptchaToken(null); setCaptchaKey((key) => key + 1); } };
  const initials = name.split(' ').filter(Boolean).map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'E';
  return <div className="space-y-6"><PageHeader title="Paramètres" subtitle="Gérez votre profil et la sécurité de votre compte." /><div className="grid gap-6 lg:grid-cols-3"><div className="lg:col-span-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><User className="h-4 w-4 text-primary" />Profil</CardTitle></CardHeader><CardContent className="space-y-4">{loading ? <p className="text-sm text-muted-foreground">Chargement du profil…</p> : <><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-primary text-lg font-semibold text-primary-foreground">{initials}</div><div><p className="font-semibold">{name || 'Élève'}</p><p className="text-sm text-muted-foreground">Élève</p></div></div><Separator /><div><Label htmlFor="name">Nom affiché</Label><Input id="name" value={name} onChange={(event) => setName(event.target.value)} className="mt-1.5" /></div><div><Label htmlFor="email">Adresse e-mail</Label><Input id="email" value={email} disabled className="mt-1.5" /></div><Button onClick={save} disabled={saving || !name.trim()}>{saving ? 'Enregistrement…' : 'Enregistrer les modifications'}</Button></>}</CardContent></Card></div><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Shield className="h-4 w-4 text-primary" />Sécurité</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Confirmez votre mot de passe actuel avant de le changer.</p><div><Label htmlFor="current-password">Mot de passe actuel</Label><Input id="current-password" type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} className="mt-1.5" autoComplete="current-password" /></div><div><Label htmlFor="new-password">Nouveau mot de passe</Label><Input id="new-password" type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} className="mt-1.5" autoComplete="new-password" /></div><div><Label htmlFor="password-confirmation">Confirmer le mot de passe</Label><Input id="password-confirmation" type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-1.5" autoComplete="new-password" /></div><Turnstile key={captchaKey} onToken={setCaptchaToken} /><Button variant="outline" className="w-full justify-start" onClick={changePassword} disabled={changing || !currentPassword || !newPassword || !confirmation}><KeyRound className="h-4 w-4" />{changing ? 'Modification…' : 'Changer le mot de passe'}</Button></CardContent></Card></div></div>;
}
