'use client';

import { apiUrl } from '@/lib/api-url';
import { useEffect, useState } from 'react';
import { KeyRound, Shield, User } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import { cachedApiGet, invalidateCacheTags } from '@/lib/api-cache';
import { PageHeader } from '@/components/shared/page-header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { toast } from 'sonner';


export default function TeacherSettingsPage() {
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [newPassword, setNewPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [changingPassword, setChangingPassword] = useState(false);
  useEffect(() => { (async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session) { setLoading(false); return; } try { setName((await cachedApiGet<{ display_name: string }>('/api/profile', 5 * 60_000, ['profile'])).display_name); } finally { setEmail(session.user.email ?? ''); setLoading(false); } })(); }, []);
  const save = async () => { const { data: { session } } = await supabase.auth.getSession(); if (!session) return; setSaving(true); try { const response = await fetch(`${apiUrl}/api/profile`, { method: 'PATCH', headers: { Authorization: `Bearer ${session.access_token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ display_name: name }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail ?? 'Impossible d’enregistrer le profil.'); invalidateCacheTags('profile'); setName(payload.display_name); toast.success('Profil enregistré'); } catch (error) { toast.error('Enregistrement impossible', { description: error instanceof Error ? error.message : undefined }); } finally { setSaving(false); } };
  const changePassword = async () => { if (newPassword.length < 8) { toast.error('Mot de passe trop court', { description: 'Utilisez au moins 8 caractères.' }); return; } if (newPassword !== confirmation) { toast.error('Les mots de passe ne correspondent pas'); return; } setChangingPassword(true); try { const { error } = await supabase.auth.updateUser({ password: newPassword }); if (error) { toast.error('Modification impossible', { description: error.message }); return; } setNewPassword(''); setConfirmation(''); toast.success('Mot de passe modifié', { description: 'Votre nouveau mot de passe est actif.' }); } catch (error) { toast.error('Modification impossible', { description: error instanceof Error ? error.message : 'Une erreur inattendue est survenue.' }); } finally { setChangingPassword(false); } };
  const initials = name.split(' ').filter(Boolean).map((part) => part[0]).join('').slice(0, 2).toUpperCase() || 'P';
  return <div className="space-y-6"><PageHeader title="Paramètres" subtitle="Gérez votre profil et la sécurité de votre compte." /><div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><User className="h-4 w-4 text-primary" />Profil</CardTitle></CardHeader><CardContent className="space-y-4">{loading ? <p className="text-sm text-muted-foreground">Chargement du profil…</p> : <><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-primary text-lg font-semibold text-primary-foreground">{initials}</div><div><p className="text-base font-semibold text-foreground">{name || 'Professeur'}</p><p className="text-sm text-muted-foreground">Professeur administrateur</p></div></div><Separator /><div><Label htmlFor="name">Nom affiché</Label><Input id="name" value={name} onChange={(event) => setName(event.target.value)} className="mt-1.5" /></div><div><Label htmlFor="email">Adresse e-mail</Label><Input id="email" value={email} disabled className="mt-1.5" /><p className="mt-1 text-xs text-muted-foreground">L’adresse e-mail est gérée par Supabase Auth.</p></div><Button onClick={save} disabled={saving || !name.trim()}>{saving ? 'Enregistrement…' : 'Enregistrer les modifications'}</Button></>}</CardContent></Card></div><div className="space-y-4"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Shield className="h-4 w-4 text-primary" />Sécurité</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">Choisissez un nouveau mot de passe pour le compte connecté.</p><div><Label htmlFor="new-password">Nouveau mot de passe</Label><Input id="new-password" type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} className="mt-1.5" autoComplete="new-password" /></div><div><Label htmlFor="password-confirmation">Confirmer le mot de passe</Label><Input id="password-confirmation" type="password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="mt-1.5" autoComplete="new-password" /></div><Button variant="outline" className="w-full justify-start" onClick={changePassword} disabled={changingPassword || !newPassword || !confirmation}><KeyRound className="h-4 w-4" />{changingPassword ? 'Modification…' : 'Changer le mot de passe'}</Button></CardContent></Card></div></div></div>;
}
