'use client';

import { apiUrl } from '@/lib/api-url';
import { useEffect, useMemo, useState } from 'react';
import { FileText, HelpCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import { cachedApiGet } from '@/lib/api-cache';
import { PageHeader } from '@/components/shared/page-header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Exercise = { id: string; title: string; publication_status: string; published_at: string | null; classes?: { code: string } };
type Question = { id: string; body: string; author: string; exercise_title: string; created_at: string };
type Activity = { id: string; type: 'publish' | 'question'; title: string; detail: string; createdAt: string };
function timeAgo(iso: string) { const seconds = Math.max(0, (Date.now() - new Date(iso).getTime()) / 1000); return seconds < 3600 ? `il y a ${Math.max(1, Math.floor(seconds / 60))} min` : seconds < 86400 ? `il y a ${Math.floor(seconds / 3600)} h` : `il y a ${Math.floor(seconds / 86400)} j`; }

export default function TeacherActivityPage() {
  const [exercises, setExercises] = useState<Exercise[]>([]); const [questions, setQuestions] = useState<Question[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { (async () => { try { const [exercisePayload, questionPayload] = await Promise.all([cachedApiGet<{ items: Exercise[] }>('/api/exercises', 5 * 60_000, ['exercises']), cachedApiGet<{ items: Question[] }>('/api/questions', 60_000, ['questions'])]); setExercises(exercisePayload.items); setQuestions(questionPayload.items); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Impossible de charger l’activité.'); } finally { setLoading(false); } })(); }, []);
  const activities = useMemo<Activity[]>(() => [...exercises.filter((item) => item.publication_status === 'publie' && item.published_at).map((item) => ({ id: `exercise-${item.id}`, type: 'publish' as const, title: 'Exercice publié', detail: `${item.title}${item.classes?.code ? ` · ${item.classes.code}` : ''}`, createdAt: item.published_at! })), ...questions.map((item) => ({ id: `question-${item.id}`, type: 'question' as const, title: `${item.author} a posé une question`, detail: `${item.exercise_title} — ${item.body}`, createdAt: item.created_at }))].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()), [exercises, questions]);
  const days = useMemo(() => Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index)); const end = new Date(date); end.setDate(end.getDate() + 1); return { label: date.toLocaleDateString('fr-FR', { weekday: 'short' }).replace('.', ''), count: questions.filter((question) => new Date(question.created_at) >= date && new Date(question.created_at) < end).length }; }), [questions]);
  const maximum = Math.max(1, ...days.map((day) => day.count));
  return <div className="space-y-6"><PageHeader title="Activité" subtitle="Événements réels liés aux exercices et aux questions." />{loading ? <Card><CardContent className="py-12 text-center text-sm text-muted-foreground">Chargement de l’activité…</CardContent></Card> : error ? <Card className="border-destructive/20"><CardContent className="py-12 text-center text-sm text-destructive">{error}</CardContent></Card> : <><Card><CardHeader><CardTitle className="text-base">Questions des sept derniers jours</CardTitle></CardHeader><CardContent><div className="flex items-end justify-between gap-2" style={{ height: '160px' }}>{days.map((day) => <div key={day.label} className="flex flex-1 flex-col items-center gap-2"><div className="flex w-full flex-1 items-end justify-center"><div className="w-full max-w-[36px] rounded-t-md bg-primary/80" style={{ height: `${(day.count / maximum) * 100}%` }} title={`${day.count} question(s)`} /></div><span className="text-xs text-muted-foreground">{day.label}</span><span className="text-xs text-muted-foreground">{day.count}</span></div>)}</div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Historique récent</CardTitle></CardHeader><CardContent className="divide-y divide-border p-0">{activities.length === 0 ? <p className="p-8 text-center text-sm text-muted-foreground">Aucune activité enregistrée pour le moment.</p> : activities.slice(0, 30).map((activity) => { const Icon = activity.type === 'publish' ? FileText : HelpCircle; const color = activity.type === 'publish' ? 'bg-primary/10 text-primary' : 'bg-accent/10 text-accent'; return <div key={activity.id} className="flex items-start gap-3 p-4"><div className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-lg ${color}`}><Icon className="h-4.5 w-4.5" /></div><div className="min-w-0 flex-1"><p className="text-sm font-medium text-foreground">{activity.title}</p><p className="mt-0.5 line-clamp-1 text-sm text-muted-foreground">{activity.detail}</p><p className="mt-1 text-xs text-muted-foreground/70">{timeAgo(activity.createdAt)}</p></div></div>; })}</CardContent></Card></>}</div>;
}
