'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, BookOpen, ChevronRight, FileText, HelpCircle, MessageCircle } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import { cachedApiGet } from '@/lib/api-cache';
import type { ClassCode, QuestionStatus } from '@/lib/types';
import { ClassCard } from '@/components/shared/class-card';
import { ExerciseCard } from '@/components/shared/exercise-card';
import { QuestionStatusBadge } from '@/components/shared/badges';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

type Exercise = { id: string; title: string; difficulty: 'facile' | 'moyen' | 'difficile'; tags: string[]; published_at: string; image_url?: string; classes?: { code: string }; chapters?: { title: string } };
type ClassItem = { id: string; code: string; name: string; chapters: unknown[]; exercise_count: number };
type Question = { id: string; exercise_id: string; exercise_title: string; body: string; reply_count: number; is_resolved: boolean; created_at: string };
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000';
function questionStatus(question: Question): QuestionStatus { return question.is_resolved ? 'resolu' : question.reply_count ? 'repondu' : 'en_attente'; }
function timeAgo(iso: string) { const seconds = Math.max(0, (Date.now() - new Date(iso).getTime()) / 1000); return seconds < 3600 ? `il y a ${Math.max(1, Math.floor(seconds / 60))} min` : seconds < 86400 ? `il y a ${Math.floor(seconds / 3600)} h` : `il y a ${Math.floor(seconds / 86400)} j`; }

export default function StudentDashboard() {
  const [classes, setClasses] = useState<ClassItem[]>([]);
  const [exercises, setExercises] = useState<Exercise[]>([]);
  const [questions, setQuestions] = useState<Question[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { (async () => { try { const payloads = await Promise.all([cachedApiGet<{ items: ClassItem[] }>('/api/classes', 5 * 60_000, ['classes']), cachedApiGet<{ items: Exercise[] }>('/api/exercises', 5 * 60_000, ['exercises']), cachedApiGet<{ items: Question[] }>('/api/questions', 60_000, ['questions'])]); setClasses(payloads[0].items); setExercises(payloads[1].items); setQuestions(payloads[2].items); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Impossible de charger le tableau de bord.'); } finally { setLoading(false); } })(); }, []);
  const pendingQuestions = useMemo(() => questions.filter((question) => !question.is_resolved), [questions]);
  const recentExercises = exercises.slice(0, 4);

  return <div className="space-y-8"><div><h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">Bonjour 👋</h1><p className="mt-1 text-sm text-muted-foreground sm:text-base">Retrouvez votre classe, vos exercices et vos discussions.</p></div>
    {loading ? <Card><CardContent className="py-14 text-center text-sm text-muted-foreground">Chargement du tableau de bord…</CardContent></Card> : error ? <Card className="border-destructive/20"><CardContent className="py-14 text-center text-sm text-destructive">{error}</CardContent></Card> : <>
      <section><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><BookOpen className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold text-foreground">Ma classe</h2></div><Link href="/eleve/classes" className="text-sm font-medium text-primary hover:underline">Tout voir</Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{classes.map((item, index) => <ClassCard key={item.id} code={item.code as ClassCode} label={item.name} description="Classe approuvée" chapterCount={item.chapters.length} exerciseCount={item.exercise_count} href="/eleve/classes" motifIndex={index} />)}</div></section>
      <section><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><FileText className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold text-foreground">Exercices disponibles</h2></div><Link href="/eleve/exercices" className="text-sm font-medium text-primary hover:underline">Tous les exercices</Link></div>{recentExercises.length === 0 ? <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Aucun exercice publié pour le moment.</CardContent></Card> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{recentExercises.map((item, index) => <ExerciseCard key={item.id} exercise={{ id: item.id, number: index + 1, title: item.title, classCode: (item.classes?.code ?? '') as ClassCode, chapter: item.chapters?.title ?? 'Sans chapitre', difficulty: item.difficulty, status: 'nouveau', publicationStatus: 'publie', viewCount: 0, questionCount: 0, publishedAt: item.published_at ?? '', tags: item.tags ?? [], artVariant: 1, imageUrl: item.image_url }} href={`/eleve/exercices/${item.id}`} />)}</div>}</section>
      <div className="grid gap-6 lg:grid-cols-3"><section className="lg:col-span-2"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><HelpCircle className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold text-foreground">Mes questions</h2></div><Link href="/eleve/questions" className="text-sm font-medium text-primary hover:underline">Tout voir</Link></div><Card><CardContent className="divide-y divide-border p-0">{pendingQuestions.length === 0 ? <p className="p-6 text-center text-sm text-muted-foreground">Aucune question en attente.</p> : pendingQuestions.slice(0, 4).map((question) => <Link key={question.id} href={`/eleve/exercices/${question.exercise_id}`} className="flex items-start gap-3 p-4 transition-colors hover:bg-secondary/40"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><MessageCircle className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-foreground">{question.exercise_title}</p><p className="mt-0.5 line-clamp-1 text-xs text-muted-foreground">{question.body}</p><p className="mt-1 text-xs text-muted-foreground/70">{timeAgo(question.created_at)} · {question.reply_count} réponse{question.reply_count > 1 ? 's' : ''}</p></div><QuestionStatusBadge status={questionStatus(question)} /></Link>)}</CardContent></Card></section>
      <section><h2 className="mb-4 text-lg font-semibold text-foreground">Accès rapide</h2><div className="space-y-3"><Link href="/eleve/exercices" className="group flex items-center gap-3 rounded-xl border border-border bg-card p-4 shadow-sm transition-all hover:border-primary/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><FileText className="h-5 w-5" /></div><div className="flex-1"><p className="text-sm font-semibold text-foreground">Parcourir les exercices</p><p className="text-xs text-muted-foreground">{exercises.length} exercice{exercises.length > 1 ? 's' : ''} disponible{exercises.length > 1 ? 's' : ''}</p></div><ChevronRight className="h-4 w-4 text-muted-foreground" /></Link><Link href="/eleve/questions" className="group flex items-center gap-3 rounded-xl border border-border bg-card p-4 shadow-sm transition-all hover:border-primary/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/10 text-accent"><HelpCircle className="h-5 w-5" /></div><div className="flex-1"><p className="text-sm font-semibold text-foreground">Mes questions</p><p className="text-xs text-muted-foreground">{pendingQuestions.length} en attente</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link></div></section></div>
    </>}</div>;
}
