'use client';

import { apiUrl } from '@/lib/api-url';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, CheckCircle2, FileText, HelpCircle, PlusCircle, Shield, Users } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';
import { cachedApiGet, peekApiCache } from '@/lib/api-cache';
import type { QuestionStatus } from '@/lib/types';
import { KPICard } from '@/components/shared/kpi-card';
import { PageHeader } from '@/components/shared/page-header';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { QuestionStatusBadge } from '@/components/shared/badges';
import { Button } from '@/components/ui/button';

type Exercise = { id: string; title: string; publication_status: 'publie' | 'brouillon' | 'depublie'; published_at: string | null; classes?: { code: string }; chapters?: { title: string } };
type Question = { id: string; exercise_id: string; exercise_title: string; body: string; author: string; reply_count: number; is_resolved: boolean; created_at: string };
type ClassItem = { student_count: number };
type Report = { id: string };
function questionStatus(question: Question): QuestionStatus { return question.is_resolved ? 'resolu' : question.reply_count ? 'repondu' : 'en_attente'; }
function timeAgo(iso: string) { const seconds = Math.max(0, (Date.now() - new Date(iso).getTime()) / 1000); return seconds < 3600 ? `il y a ${Math.max(1, Math.floor(seconds / 60))} min` : seconds < 86400 ? `il y a ${Math.floor(seconds / 3600)} h` : `il y a ${Math.floor(seconds / 86400)} j`; }

export default function TeacherDashboard() {
  const cachedExercises = peekApiCache<{ items: Exercise[] }>('/api/exercises'); const cachedQuestions = peekApiCache<{ items: Question[] }>('/api/questions'); const cachedClasses = peekApiCache<{ items: ClassItem[] }>('/api/classes'); const cachedReports = peekApiCache<{ items: Report[] }>('/api/moderation/reports');
  const [exercises, setExercises] = useState<Exercise[]>(() => cachedExercises?.items ?? []); const [questions, setQuestions] = useState<Question[]>(() => cachedQuestions?.items ?? []); const [classes, setClasses] = useState<ClassItem[]>(() => cachedClasses?.items ?? []); const [reports, setReports] = useState<Report[]>(() => cachedReports?.items ?? []); const [loading, setLoading] = useState(!cachedExercises || !cachedQuestions || !cachedClasses || !cachedReports); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (cachedExercises && cachedQuestions && cachedClasses && cachedReports) return; (async () => { try { const payloads = await Promise.all([cachedApiGet<{ items: Exercise[] }>('/api/exercises', 5 * 60_000, ['exercises']), cachedApiGet<{ items: Question[] }>('/api/questions', 60_000, ['questions']), cachedApiGet<{ items: ClassItem[] }>('/api/classes', 5 * 60_000, ['classes']), cachedApiGet<{ items: Report[] }>('/api/moderation/reports', 5 * 60_000, ['reports'])]); setExercises(payloads[0].items); setQuestions(payloads[1].items); setClasses(payloads[2].items); setReports(payloads[3].items); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : 'Impossible de charger le tableau de bord.'); } finally { setLoading(false); } })(); }, []);
  const publishedCount = exercises.filter((item) => item.publication_status === 'publie').length;
  const pendingQuestions = useMemo(() => questions.filter((item) => !item.is_resolved && item.reply_count === 0), [questions]);
  const resolvedCount = questions.filter((item) => item.is_resolved).length;
  const activeStudents = classes.reduce((count, item) => count + item.student_count, 0);
  const recentExercises = exercises.filter((item) => item.publication_status === 'publie').slice(0, 4);

  return <div className="space-y-8"><PageHeader title="Tableau de bord" subtitle="Voici un aperçu en temps réel de votre activité pédagogique."><Link href="/prof/ajouter"><Button size="sm"><PlusCircle className="h-4 w-4" />Ajouter un exercice</Button></Link></PageHeader>
    {loading ? <Card><CardContent className="py-14 text-center text-sm text-muted-foreground">Chargement du tableau de bord…</CardContent></Card> : error ? <Card className="border-destructive/20"><CardContent className="py-14 text-center text-sm text-destructive">{error}</CardContent></Card> : <>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><KPICard icon={FileText} label="Exercices publiés" value={String(publishedCount)} accent="primary" /><KPICard icon={HelpCircle} label="Questions en attente" value={String(pendingQuestions.length)} accent="warning" /><KPICard icon={CheckCircle2} label="Questions résolues" value={String(resolvedCount)} accent="success" /><KPICard icon={Users} label="Élèves actifs" value={String(activeStudents)} accent="accent" /></div>
      <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader className="flex flex-row items-center justify-between space-y-0"><CardTitle className="text-base">Exercices récemment publiés</CardTitle><Link href="/prof/exercices" className="text-sm font-medium text-primary hover:underline">Tout voir</Link></CardHeader><CardContent className="divide-y divide-border p-0">{recentExercises.length === 0 ? <p className="p-6 text-center text-sm text-muted-foreground">Aucun exercice publié pour le moment.</p> : recentExercises.map((item) => <Link key={item.id} href={`/prof/exercices/${item.id}`} className="flex items-start gap-3 p-4 transition-colors hover:bg-secondary/40"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary"><FileText className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-foreground">{item.title}</p><p className="text-xs text-muted-foreground">{item.classes?.code ?? ''} · {item.chapters?.title ?? 'Sans chapitre'}</p></div></Link>)}</CardContent></Card>
      <Card><CardHeader className="flex flex-row items-center justify-between space-y-0"><CardTitle className="text-base">Questions à traiter</CardTitle><Link href="/prof/questions" className="text-sm font-medium text-primary hover:underline">Tout voir</Link></CardHeader><CardContent className="divide-y divide-border p-0">{pendingQuestions.length === 0 ? <p className="p-6 text-center text-sm text-muted-foreground">Aucune question en attente.</p> : pendingQuestions.slice(0, 4).map((item) => <Link key={item.id} href="/prof/questions" className="flex items-start gap-3 p-4 transition-colors hover:bg-secondary/40"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-warning/10 text-warning"><HelpCircle className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-foreground">{item.exercise_title}</p><p className="line-clamp-1 text-xs text-muted-foreground">{item.body}</p><p className="mt-0.5 text-xs text-muted-foreground/70">{item.author} · {timeAgo(item.created_at)}</p></div><QuestionStatusBadge status={questionStatus(item)} /></Link>)}</CardContent></Card></div>
      <div className="grid gap-4 sm:grid-cols-3"><Link href="/prof/ajouter" className="group flex items-center gap-3 rounded-xl border border-border bg-card p-4 shadow-sm transition-all hover:border-primary/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><PlusCircle className="h-5 w-5" /></div><div className="flex-1"><p className="text-sm font-semibold text-foreground">Ajouter un exercice</p><p className="text-xs text-muted-foreground">Créer un nouvel énoncé</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link><Link href="/prof/moderation" className="group flex items-center gap-3 rounded-xl border border-border bg-card p-4 shadow-sm transition-all hover:border-primary/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-warning/10 text-warning"><Shield className="h-5 w-5" /></div><div className="flex-1"><p className="text-sm font-semibold text-foreground">Modération</p><p className="text-xs text-muted-foreground">{reports.length} signalement{reports.length > 1 ? 's' : ''} en attente</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link><Link href="/prof/exercices" className="group flex items-center gap-3 rounded-xl border border-border bg-card p-4 shadow-sm transition-all hover:border-primary/30 hover:shadow-md"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-accent/10 text-accent"><FileText className="h-5 w-5" /></div><div className="flex-1"><p className="text-sm font-semibold text-foreground">Gérer mes exercices</p><p className="text-xs text-muted-foreground">{publishedCount} exercice{publishedCount > 1 ? 's' : ''} publié{publishedCount > 1 ? 's' : ''}</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link></div>
    </>}</div>;
}
